version: '3'

services:
  db:
    image: postgres
    ports:
      - '5432:5432'
    environment:
      - POSTGRES_USER=developer
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=example_db
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data

volumes:
  postgresql:
  postgresql_data:
